### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by timea-techgirl** [lyonna/ChromeOfflineInstallerDownloadAPI#1]
Thanks for this amazing script. I love it.
It would be awesome if you could provide an exe file so that it is easy to run :)
On my Windows 10 machine, I get this error. 

Error:
```
C:\php>php.exe coi.php
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in coi.php on line 81

Warning: Invalid argument supplied for foreach() in coi.php on line 81
{"win_stable_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"win_stable_x86":{"version":null,"size":null,"sha256":null,"urls":[]},"win_beta_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"win_beta_x86":{"version":null,"size":null,"sha256":null,"urls":[]},"win_dev_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"win_dev_x86":{"version":null,"size":null,"sha256":null,"urls":[]},"win_canary_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"win_canary_x86":{"version":null,"size":null,"sha256":null,"urls":[]},"mac_stable_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"mac_beta_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"mac_dev_x64":{"version":null,"size":null,"sha256":null,"urls":[]},"mac_canary_x64":{"version":null,"size":null,"sha256":null,"urls":[]}}

```

I found some answers on the internet to fix this error. For example,
> foreach works only if the variable is either an array or an object.
> 
> If you provide something else you see the error you see:
> Warning: Invalid argument supplied for foreach() in ...
> 
> To make that error stop, ensure that the variable you pass to foreach is either an array or an object.

Can you please fix this? Thanks

**Comment by lyonna** [comment]
@timea-techgirl Thanks for feedback. I'll look into it this weekend.
I may also write a program in Golang and compile it into .exe file if I have free time.

**Comment by timea-techgirl** [comment]
@lyonna Thank you so much for the response
Inserting this line didn't make any difference, I got the same error :(

Oh, I would be grateful and gladly wait, appreciate it :)

**Comment by timea-techgirl** [comment]
@lyonna Thank you so much for the response
Inserting this line works but without internet access, it's the same error.

It would be great if the resulting json output is automatically parsed/readable.
So happy with this script.

Oh, I would be grateful and gladly wait, appreciate it :)

**Comment by lyonna** [comment]
@timea-techgirl `Error` labels added. #9b9e9cfd1c0efa3ee345e7569b52fb3f5085423e

**Comment by timea-techgirl** [comment]
@lyonna Thanks, of course, it's good to know what went wrong :)

**Comment by lyonna** [comment]
@timea-techgirl Resolved

**Comment by timea-techgirl** [comment]
> @timea-techgirl Resolved

Thanks, here are my results..
Without internet access:
`{"win_stable_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_stable_x86":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_beta_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_beta_x86":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_dev_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_dev_x86":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_canary_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"win_canary_x86":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"mac_stable_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"mac_beta_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"mac_dev_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]},"mac_canary_x64":{"error":"Failed to connect to tools.google.com port 443: Bad access","version":"","size":0,"sha256":"","urls":[]}}`

With internet access:
`{"win_stable_x64":{"error":"Failed to parse XML text","version":"","size":0,"sha256":"","urls":[]},"win_stable_x86":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"win_beta_x64":{"error":"Failed to parse XML text","version":"","size":0,"sha256":"","urls":[]},"win_beta_x86":{"error":"Failed to parse XML text","version":"","size":0,"sha256":"","urls":[]},"win_dev_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"win_dev_x86":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"win_canary_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"win_canary_x86":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"mac_stable_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"mac_beta_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"mac_dev_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]},"mac_canary_x64":{"error":"SSL certificate problem: unable to get local issuer certificate","version":"","size":0,"sha256":"","urls":[]}}`

**Comment by timea-techgirl** [comment]
Adding this line again solved it,
`curl_setopt($ch[$key], CURLOPT_SSL_VERIFYPEER, 0);`

Can the json output be parsed automatically to copy links easily?
https://stackoverflow.com/questions/17016506/how-to-parse-json-and-access-results
https://www.php.net/manual/en/function.json-decode.php

Do I need to keep php installed or is it possible to make an exe? Thanks a lot

**Comment by lyonna** [comment]
It is designed as an API with json format.
Maybe [https://chromeinstaller.herokuapp.com/](https://chromeinstaller.herokuapp.com/) is what you need.

**Comment by timea-techgirl** [comment]
@lyonna Any option now to run this without php?
