### ISSUE TITLE
Windows Canary and Dev channel links issue

### ISSUE THREAD

**Issue by crazycanuk11** [lyonna/ChromeOfflineInstallerDownloadAPI#3]
Can't get Windows Canary and Dev channel links anymore.
Canary for Windows is completely gone and Dev for Windows will no longer be updated.

**Comment by crazycanuk11** [comment]
Now only stable_win and mac links are generated, everything else is zero.

**Comment by lyonna** [comment]
> Now only stable_win and mac links are generated, everything else is zero.

Resolved.
e7a72d209b25f53bdb4f5c1fb3bb0f413f131d2e

**Comment by crazycanuk11** [comment]
It all worked at first, but now it doesn't.
Apparently there has been a change somewhere.
If you have time, review this script.
Everything will stop forever on this message
Please wait...
Please wait while the data you requested is being retrieved.

**Comment by crazycanuk11** [comment]
Thanks, yes now is everything OK.
